[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "tqdm",
    "ipywidgets",
    "datasets",
    "sentencepiece",
    "sacrebleu==1.*",
    "transformers",
]
build-backend = "setuptools.build_meta"